# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-04 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_remove_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_occurrence',
            field=models.IntegerField(default=1, verbose_name=1),
            preserve_default=False,
        ),
    ]
