# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-04 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_question_question_occurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_occurrence',
            field=models.IntegerField(),
        ),
    ]
