# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_auto_20170304_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_occurrence',
            field=models.IntegerField(default=0, verbose_name=1),
        ),
    ]
